### ISSUE TITLE
How to use wl-mirror?

### ISSUE THREAD

**Issue by sebas891** [Ferdi265/wl-mirror#22] opened 2023-04-21 03:06 UTC
I'm trying to figure how to use wl-mirror. I'm on Debian testing using gnome and wayland, I don't understand the parameter I should put in the <output> when running the command wl-mirror. What would be examples of output?

My use case is that I have projector as a second screen connected to my laptop and I would to monitor the output of the projector in a window on my main laptop screen.  Can I accomplish that with wl-mirror?
Any help will be appreciated.

Cheers,

```
$ xrandr --query | grep '\bconnected\b'
XWAYLAND80 connected primary 1920x1080+0+1080 (normal left inverted right x axis y axis) 310mm x 170mm
XWAYLAND82 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 520mm x 290mm

```

**Comment by Ferdi265** [comment] 2023-04-21 10:27
Hi! wl-mirror currently only supports Wayland compositors based on wlroots, such as [sway](https://swaywm.org) or [hyprland](https://hyprland.org) (haven't tested it on hyprland yet, but it should work).

Support for the two other big compositors (KDE and Gnome) is planned, but not implemented yet. This would require supporting the XDG Desktop Portals screenshare API (#16) and negotiating server or client-side window decorations (#17) and of course a bunch of testing.

On sway, you would start `wl-mirror` with a command like `wl-mirror eDP-1` or `wl-mirror HDMI-A-1`, which will open a resizable window containing a view of the specified output that you can move wherever you want. Note that the names you can pass to `wl-mirror` are not be the names you get listed from `xrandr`. On sway you can get a list of the available outputs with `swaymsg -t get_outputs`

So yes, your use case would be easily solved by `wl-mirror` if you were either on sway or if Gnome support were finished already.

I'm marking this issue as a duplicate of #17 since you are using Gnome, which is not supported yet.

**Closed by Ferdi265** 2023-04-21 10:27 UTC

**Comment by sebas891** [comment] 2023-04-21 19:41
Many thanks for the clear and complet answer!  For now, I give a try to Sway. I'll be there to test the gnome support when it comes around. 
Thanks for all the work on wl-mirror!

**Comment by Thaodan** [comment] 2023-04-22 21:56
> On sway, you would start `wl-mirror` with a command like `wl-mirror eDP-1` or `wl-mirror HDMI-A-1`, which will open a resizable window containing a view of the specified output that you can move wherever you want. Note that the names you can pass to `wl-mirror` are not be the names you get listed from `xrandr`. On sway you can get a list of the available outputs with `swaymsg -t get_outputs`

How would you make sway "ignore" those screens? I have setup where I have DP-1, DP-3 and HDMI-A-1. I mirror DP-3 on HDMI-A-1. I don't want Sway to spawn work spaces on the screen that is mirrored.

Hyprland can kinda do that but is rather unstable.

**Comment by Ferdi265** [comment] 2023-04-23 07:31
You can't really ignore them but you can prevent your mouse from going there by setting their coordinates so that there is a gap between them.

e.g. if you use the two DP screens and want to mirror to the HDMI one:

DP-1 at 0,0 with 1920x1080, DP-3 at 1920,0 with 1920x1080 (contiguous, no gap), HDMI-A-1 at 3900,0 with 1920x1080 (gap of 60 pixels)

it also helps if you make the active workspace on HDMI-A-1 something that you are unlikely to use, e.g. workspace 11.

With a gap like this, sway will prevent you from moving your mouse to the gapped off monitor normally, but you can still switch to it using the keyboard and by focusing the workspace that lives on that monitor.

**Comment by Thaodan** [comment] 2023-04-23 14:30
That sounds like a good workaround I will try.

There was another PR to built something inside sway with a wlroots PR.
